### ISSUE TITLE
Licence violation

### ISSUE THREAD

**Issue by TsunayoshiSawada** [Teameviral/Skynoid#1]
Your Kang for https://github.com/pokurt/Nana-Remix 
You cant go on changing licenses like this, GPLV3 requires you to use the same license 

When yall make-believe teams have the audacity to copy others code down to the brim, at least have the decency to respect the license. 

TLDR: Fix the license and the commit history unless you want legal prosecutions on your account.

**Comment by Teameviral** [comment]
I can do it because the project is public

**Comment by TsunayoshiSawada** [comment]
No, you did it because you are challenged. 
You can also go and jump from a roof, doesn't mean jumping from a roof is the right thing to do. 

This license change and commit history wipe doesn't make you guys look like pros, it makes you look like leechers, the termites of the open-source world. 
Grow up!

**Comment by Teameviral** [comment]
I have already deleted old license.

**Comment by TsunayoshiSawada** [comment]
This license change and commit history wipe doesn't make you guys look like pros, it makes you look like leechers, the termites of the open-source world.
Keep leeching, you are welcome on behalf of me and my friends. Termites
